### ISSUE TITLE
[COSMOVERSE 2022-09-27] Feedbacks 

### ISSUE THREAD

**Issue by pwnh4** [xplrz/gnoland-workshop#3]
Gno.land is still an early project and the core team goal is to improve its developer experience. Use this ticket to make feedbacks to the team!

Drop any issue / bug / error / general feedback you have during the Medellin Cosmoverse 2022 Gnoland workshop below:

**Comment by pwnh4** [comment]
* should not have to cp something in the cloned repo (p/hello): gnodev should automatically support non-published local package?
* add an example using simple storage persistence

**Comment by leobragaz** [comment]
Hi, need some test tokens: g1zwlx0xs6944f975j6h30cp9azamcxh7lp8j6ar
