### ISSUE TITLE
no Go files in....

### ISSUE THREAD

**Issue by r3v4s** [xplrz/gnoland-workshop#6]
![image](https://user-images.githubusercontent.com/104744707/196345485-46d562be-2088-4be5-8264-af84f46ed65f.png)

here is screenshot of what happened.
looks like gnodev just looking in current directory (blahblah~~/00-hello-realm) rather than target directory given via cli (./r/solve)

go version is `1.19`
gnodev sha256 is `1d8398dd0771e4523cc6c5d2a9925e705bb7d393f666ead7973d48b01e10f37e`
 i just cloned fresh copy of gnolang/gno, so it shoule be latest version.

**Comment by moul** [comment]
Will be fixed with this: https://github.com/gnolang/gno/pull/359
